version: 2

archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
    - make tfgen
builds:
  - binary: pulumi-resource-pgedge
    dir: provider
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      - -X github.com/pgEdge/pulumi-pgedge/provider/pkg/version.Version={{.Tag }}
    main: ./cmd/pulumi-resource-pgedge/
release:
  disable: false
  prerelease: auto
