// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge
{
    public static class GetSSHKeys
    {
        /// <summary>
        /// Data source for pgEdge SSH keys.
        /// </summary>
        public static Task<GetSSHKeysResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSSHKeysResult>("pgedge:index/getSSHKeys:getSSHKeys", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Data source for pgEdge SSH keys.
        /// </summary>
        public static Output<GetSSHKeysResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSSHKeysResult>("pgedge:index/getSSHKeys:getSSHKeys", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetSSHKeysResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetSSHKeysSshKeyResult> SshKeys;

        [OutputConstructor]
        private GetSSHKeysResult(
            string id,

            ImmutableArray<Outputs.GetSSHKeysSshKeyResult> sshKeys)
        {
            Id = id;
            SshKeys = sshKeys;
        }
    }
}
