// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pgedge

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pgEdge/pulumi-pgedge/sdk/go/pgedge/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "pgedge:index/backupStore:BackupStore":
		r = &BackupStore{}
	case "pgedge:index/cloudAccount:CloudAccount":
		r = &CloudAccount{}
	case "pgedge:index/cluster:Cluster":
		r = &Cluster{}
	case "pgedge:index/database:Database":
		r = &Database{}
	case "pgedge:index/sSHKey:SSHKey":
		r = &SSHKey{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:pgedge" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"pgedge",
		"index/backupStore",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"pgedge",
		"index/cloudAccount",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"pgedge",
		"index/cluster",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"pgedge",
		"index/database",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"pgedge",
		"index/sSHKey",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"pgedge",
		&pkg{version},
	)
}
