# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .cluster import *
from .database import *
from .get_clusters import *
from .get_databases import *
from .provider import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pgEdge_pulumi_pgedge.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pgEdge_pulumi_pgedge.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "pgedge",
  "mod": "index/cluster",
  "fqn": "pgEdge_pulumi_pgedge",
  "classes": {
   "pgedge:index/cluster:Cluster": "Cluster"
  }
 },
 {
  "pkg": "pgedge",
  "mod": "index/database",
  "fqn": "pgEdge_pulumi_pgedge",
  "classes": {
   "pgedge:index/database:Database": "Database"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "pgedge",
  "token": "pulumi:providers:pgedge",
  "fqn": "pgEdge_pulumi_pgedge",
  "class": "Provider"
 }
]
"""
)
