// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Outputs
{

    [OutputType]
    public sealed class ClusterNode
    {
        public readonly string? AvailabilityZone;
        public readonly string InstanceType;
        public readonly string Name;
        public readonly string Region;
        public readonly int? VolumeIops;
        public readonly int? VolumeSize;
        public readonly string? VolumeType;

        [OutputConstructor]
        private ClusterNode(
            string? availabilityZone,

            string instanceType,

            string name,

            string region,

            int? volumeIops,

            int? volumeSize,

            string? volumeType)
        {
            AvailabilityZone = availabilityZone;
            InstanceType = instanceType;
            Name = name;
            Region = region;
            VolumeIops = volumeIops;
            VolumeSize = volumeSize;
            VolumeType = volumeType;
        }
    }
}
