// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Outputs
{

    [OutputType]
    public sealed class ClusterNetwork
    {
        /// <summary>
        /// CIDR range for the network
        /// </summary>
        public readonly string Cidr;
        public readonly ImmutableArray<string> PublicSubnets;
        /// <summary>
        /// Region of the network
        /// </summary>
        public readonly string Region;

        [OutputConstructor]
        private ClusterNetwork(
            string cidr,

            ImmutableArray<string> publicSubnets,

            string region)
        {
            Cidr = cidr;
            PublicSubnets = publicSubnets;
            Region = region;
        }
    }
}
