// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Outputs
{

    [OutputType]
    public sealed class ClusterNodeGroups
    {
        public readonly ImmutableArray<Outputs.ClusterNodeGroupsAw> Aws;
        public readonly ImmutableArray<Outputs.ClusterNodeGroupsAzure> Azures;
        public readonly ImmutableArray<Outputs.ClusterNodeGroupsGoogle> Googles;

        [OutputConstructor]
        private ClusterNodeGroups(
            ImmutableArray<Outputs.ClusterNodeGroupsAw> aws,

            ImmutableArray<Outputs.ClusterNodeGroupsAzure> azures,

            ImmutableArray<Outputs.ClusterNodeGroupsGoogle> googles)
        {
            Aws = aws;
            Azures = azures;
            Googles = googles;
        }
    }
}
