// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Outputs
{

    [OutputType]
    public sealed class ClusterNetwork
    {
        /// <summary>
        /// CIDR of the network
        /// </summary>
        public readonly string Cidr;
        /// <summary>
        /// Whether the network is external
        /// </summary>
        public readonly bool? External;
        /// <summary>
        /// External ID of the network
        /// </summary>
        public readonly string? ExternalId;
        /// <summary>
        /// Name of the network
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// List of private subnets
        /// </summary>
        public readonly ImmutableArray<string> PrivateSubnets;
        /// <summary>
        /// List of public subnets
        /// </summary>
        public readonly ImmutableArray<string> PublicSubnets;
        /// <summary>
        /// Region of the network
        /// </summary>
        public readonly string Region;

        [OutputConstructor]
        private ClusterNetwork(
            string cidr,

            bool? external,

            string? externalId,

            string? name,

            ImmutableArray<string> privateSubnets,

            ImmutableArray<string> publicSubnets,

            string region)
        {
            Cidr = cidr;
            External = external;
            ExternalId = externalId;
            Name = name;
            PrivateSubnets = privateSubnets;
            PublicSubnets = publicSubnets;
            Region = region;
        }
    }
}
