// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Outputs
{

    [OutputType]
    public sealed class DatabaseRole
    {
        public readonly bool? BypassRls;
        public readonly int? ConnectionLimit;
        public readonly bool? CreateDb;
        public readonly bool? CreateRole;
        public readonly bool? Inherit;
        public readonly bool? Login;
        public readonly string? Name;
        public readonly bool? Replication;
        public readonly bool? Superuser;

        [OutputConstructor]
        private DatabaseRole(
            bool? bypassRls,

            int? connectionLimit,

            bool? createDb,

            bool? createRole,

            bool? inherit,

            bool? login,

            string? name,

            bool? replication,

            bool? superuser)
        {
            BypassRls = bypassRls;
            ConnectionLimit = connectionLimit;
            CreateDb = createDb;
            CreateRole = createRole;
            Inherit = inherit;
            Login = login;
            Name = name;
            Replication = replication;
            Superuser = superuser;
        }
    }
}
