// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Outputs
{

    [OutputType]
    public sealed class DatabaseComponent
    {
        public readonly string? Id;
        public readonly string? Name;
        public readonly string? ReleaseDate;
        public readonly string? Status;
        public readonly string? Version;

        [OutputConstructor]
        private DatabaseComponent(
            string? id,

            string? name,

            string? releaseDate,

            string? status,

            string? version)
        {
            Id = id;
            Name = name;
            ReleaseDate = releaseDate;
            Status = status;
            Version = version;
        }
    }
}
