// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Outputs
{

    [OutputType]
    public sealed class DatabaseBackupsConfigSchedule
    {
        /// <summary>
        /// Cron expression for the schedule.
        /// </summary>
        public readonly string? CronExpression;
        /// <summary>
        /// Unique identifier for the backup config.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// Type of the repository.
        /// </summary>
        public readonly string? Type;

        [OutputConstructor]
        private DatabaseBackupsConfigSchedule(
            string? cronExpression,

            string? id,

            string? type)
        {
            CronExpression = cronExpression;
            Id = id;
            Type = type;
        }
    }
}
