// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Outputs
{

    [OutputType]
    public sealed class GetClustersClusterNodeGroupsResult
    {
        public readonly ImmutableArray<Outputs.GetClustersClusterNodeGroupsAwResult> Aws;
        public readonly ImmutableArray<Outputs.GetClustersClusterNodeGroupsAzureResult> Azures;
        public readonly ImmutableArray<Outputs.GetClustersClusterNodeGroupsGoogleResult> Googles;

        [OutputConstructor]
        private GetClustersClusterNodeGroupsResult(
            ImmutableArray<Outputs.GetClustersClusterNodeGroupsAwResult> aws,

            ImmutableArray<Outputs.GetClustersClusterNodeGroupsAzureResult> azures,

            ImmutableArray<Outputs.GetClustersClusterNodeGroupsGoogleResult> googles)
        {
            Aws = aws;
            Azures = azures;
            Googles = googles;
        }
    }
}
