// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Outputs
{

    [OutputType]
    public sealed class GetClustersClusterFirewallRuleResult
    {
        /// <summary>
        /// Name of the firewall rule
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Port for the firewall rule
        /// </summary>
        public readonly int Port;
        /// <summary>
        /// Sources for the firewall rule
        /// </summary>
        public readonly ImmutableArray<string> Sources;

        [OutputConstructor]
        private GetClustersClusterFirewallRuleResult(
            string name,

            int port,

            ImmutableArray<string> sources)
        {
            Name = name;
            Port = port;
            Sources = sources;
        }
    }
}
