// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Outputs
{

    [OutputType]
    public sealed class GetDatabasesDatabaseTableStatusResult
    {
        /// <summary>
        /// Aligned of the table
        /// </summary>
        public readonly bool Aligned;
        /// <summary>
        /// Node name of the table
        /// </summary>
        public readonly string NodeName;
        /// <summary>
        /// Present of the table
        /// </summary>
        public readonly bool Present;
        /// <summary>
        /// Replicating of the table
        /// </summary>
        public readonly bool Replicating;

        [OutputConstructor]
        private GetDatabasesDatabaseTableStatusResult(
            bool aligned,

            string nodeName,

            bool present,

            bool replicating)
        {
            Aligned = aligned;
            NodeName = nodeName;
            Present = present;
            Replicating = replicating;
        }
    }
}
