// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Outputs
{

    [OutputType]
    public sealed class GetDatabasesDatabaseNodeExtensionsErrorsResult
    {
        /// <summary>
        /// Error code anim9ef
        /// </summary>
        public readonly string Anim9ef;
        /// <summary>
        /// Error code enim3b
        /// </summary>
        public readonly string Enim3b;
        /// <summary>
        /// Error code laborumd
        /// </summary>
        public readonly string Laborumd;
        /// <summary>
        /// Error code mollit267
        /// </summary>
        public readonly string Mollit267;

        [OutputConstructor]
        private GetDatabasesDatabaseNodeExtensionsErrorsResult(
            string anim9ef,

            string enim3b,

            string laborumd,

            string mollit267)
        {
            Anim9ef = anim9ef;
            Enim3b = enim3b;
            Laborumd = laborumd;
            Mollit267 = mollit267;
        }
    }
}
