// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Outputs
{

    [OutputType]
    public sealed class GetDatabasesDatabaseRoleResult
    {
        /// <summary>
        /// Bypass RLS
        /// </summary>
        public readonly bool BypassRls;
        /// <summary>
        /// Connection limit
        /// </summary>
        public readonly int ConnectionLimit;
        /// <summary>
        /// Create database
        /// </summary>
        public readonly bool CreateDb;
        /// <summary>
        /// Create role
        /// </summary>
        public readonly bool CreateRole;
        /// <summary>
        /// Inherit
        /// </summary>
        public readonly bool Inherit;
        /// <summary>
        /// Login
        /// </summary>
        public readonly bool Login;
        /// <summary>
        /// Name of the component
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Replication
        /// </summary>
        public readonly bool Replication;
        /// <summary>
        /// Superuser
        /// </summary>
        public readonly bool Superuser;

        [OutputConstructor]
        private GetDatabasesDatabaseRoleResult(
            bool bypassRls,

            int connectionLimit,

            bool createDb,

            bool createRole,

            bool inherit,

            bool login,

            string name,

            bool replication,

            bool superuser)
        {
            BypassRls = bypassRls;
            ConnectionLimit = connectionLimit;
            CreateDb = createDb;
            CreateRole = createRole;
            Inherit = inherit;
            Login = login;
            Name = name;
            Replication = replication;
            Superuser = superuser;
        }
    }
}
