// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Outputs
{

    [OutputType]
    public sealed class GetDatabasesDatabaseNodeResult
    {
        public readonly Outputs.GetDatabasesDatabaseNodeConnectionResult Connection;
        public readonly Outputs.GetDatabasesDatabaseNodeLocationResult Location;
        /// <summary>
        /// Name of the database
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetDatabasesDatabaseNodeResult(
            Outputs.GetDatabasesDatabaseNodeConnectionResult connection,

            Outputs.GetDatabasesDatabaseNodeLocationResult location,

            string name)
        {
            Connection = connection;
            Location = location;
            Name = name;
        }
    }
}
