// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Outputs
{

    [OutputType]
    public sealed class GetDatabasesDatabaseBackupsConfigScheduleResult
    {
        public readonly string CronExpression;
        /// <summary>
        /// Backup configuration ID
        /// </summary>
        public readonly string Id;
        public readonly string Type;

        [OutputConstructor]
        private GetDatabasesDatabaseBackupsConfigScheduleResult(
            string cronExpression,

            string id,

            string type)
        {
            CronExpression = cronExpression;
            Id = id;
            Type = type;
        }
    }
}
