// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Outputs
{

    [OutputType]
    public sealed class GetDatabasesDatabaseNodeLocationResult
    {
        /// <summary>
        /// Code of the location
        /// </summary>
        public readonly string Code;
        /// <summary>
        /// Country of the location
        /// </summary>
        public readonly string Country;
        /// <summary>
        /// Latitude of the location
        /// </summary>
        public readonly double Latitude;
        /// <summary>
        /// Longitude of the location
        /// </summary>
        public readonly double Longitude;
        /// <summary>
        /// Name of the database
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Region of the location
        /// </summary>
        public readonly string Region;

        [OutputConstructor]
        private GetDatabasesDatabaseNodeLocationResult(
            string code,

            string country,

            double latitude,

            double longitude,

            string name,

            string region)
        {
            Code = code;
            Country = country;
            Latitude = latitude;
            Longitude = longitude;
            Name = name;
            Region = region;
        }
    }
}
