// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Outputs
{

    [OutputType]
    public sealed class GetDatabasesDatabaseNodeDistanceMeasurementResult
    {
        /// <summary>
        /// Distance from a reference point
        /// </summary>
        public readonly double Distance;
        /// <summary>
        /// Latitude of the reference point
        /// </summary>
        public readonly double FromLatitude;
        /// <summary>
        /// Longitude of the reference point
        /// </summary>
        public readonly double FromLongitude;
        /// <summary>
        /// Unit of distance measurement
        /// </summary>
        public readonly string Unit;

        [OutputConstructor]
        private GetDatabasesDatabaseNodeDistanceMeasurementResult(
            double distance,

            double fromLatitude,

            double fromLongitude,

            string unit)
        {
            Distance = distance;
            FromLatitude = fromLatitude;
            FromLongitude = fromLongitude;
            Unit = unit;
        }
    }
}
