// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Outputs
{

    [OutputType]
    public sealed class GetDatabasesDatabaseNodeResult
    {
        /// <summary>
        /// Node connection details
        /// </summary>
        public readonly Outputs.GetDatabasesDatabaseNodeConnectionResult Connection;
        /// <summary>
        /// Node extensions
        /// </summary>
        public readonly Outputs.GetDatabasesDatabaseNodeExtensionsResult Extensions;
        /// <summary>
        /// Node location
        /// </summary>
        public readonly Outputs.GetDatabasesDatabaseNodeLocationResult Location;
        /// <summary>
        /// Name of the component
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Region of the location
        /// </summary>
        public readonly Outputs.GetDatabasesDatabaseNodeRegionResult Region;

        [OutputConstructor]
        private GetDatabasesDatabaseNodeResult(
            Outputs.GetDatabasesDatabaseNodeConnectionResult connection,

            Outputs.GetDatabasesDatabaseNodeExtensionsResult extensions,

            Outputs.GetDatabasesDatabaseNodeLocationResult location,

            string name,

            Outputs.GetDatabasesDatabaseNodeRegionResult region)
        {
            Connection = connection;
            Extensions = extensions;
            Location = location;
            Name = name;
            Region = region;
        }
    }
}
