// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Outputs
{

    [OutputType]
    public sealed class GetDatabasesDatabaseBackupsConfigRepositoryResult
    {
        public readonly string AzureAccount;
        public readonly string AzureContainer;
        public readonly string AzureEndpoint;
        public readonly string BackupStoreId;
        public readonly string BasePath;
        public readonly string GcsBucket;
        public readonly string GcsEndpoint;
        /// <summary>
        /// Backup configuration ID
        /// </summary>
        public readonly string Id;
        public readonly int RetentionFull;
        public readonly string RetentionFullType;
        public readonly string S3Bucket;
        public readonly string S3Endpoint;
        public readonly string S3Region;
        public readonly string Type;

        [OutputConstructor]
        private GetDatabasesDatabaseBackupsConfigRepositoryResult(
            string azureAccount,

            string azureContainer,

            string azureEndpoint,

            string backupStoreId,

            string basePath,

            string gcsBucket,

            string gcsEndpoint,

            string id,

            int retentionFull,

            string retentionFullType,

            string s3Bucket,

            string s3Endpoint,

            string s3Region,

            string type)
        {
            AzureAccount = azureAccount;
            AzureContainer = azureContainer;
            AzureEndpoint = azureEndpoint;
            BackupStoreId = backupStoreId;
            BasePath = basePath;
            GcsBucket = gcsBucket;
            GcsEndpoint = gcsEndpoint;
            Id = id;
            RetentionFull = retentionFull;
            RetentionFullType = retentionFullType;
            S3Bucket = s3Bucket;
            S3Endpoint = s3Endpoint;
            S3Region = s3Region;
            Type = type;
        }
    }
}
