// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ClusterFirewall {
    /**
     * Port for the firewall rule
     */
    port?: pulumi.Input<number>;
    /**
     * Sources for the firewall rule
     */
    sources?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Type of the firewall rule
     */
    type?: pulumi.Input<string>;
}

export interface ClusterNodeGroups {
    aws?: pulumi.Input<pulumi.Input<inputs.ClusterNodeGroupsAw>[]>;
    azures?: pulumi.Input<pulumi.Input<inputs.ClusterNodeGroupsAzure>[]>;
    googles?: pulumi.Input<pulumi.Input<inputs.ClusterNodeGroupsGoogle>[]>;
}

export interface ClusterNodeGroupsAw {
    /**
     * Availability zones of the AWS node group
     */
    availabilityZones?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * CIDR of the AWS node group
     */
    cidr?: pulumi.Input<string>;
    /**
     * Instance type of the AWS node group
     */
    instanceType?: pulumi.Input<string>;
    /**
     * Node location of the AWS node group
     */
    nodeLocation?: pulumi.Input<string>;
    nodes?: pulumi.Input<pulumi.Input<inputs.ClusterNodeGroupsAwNode>[]>;
    privateSubnets?: pulumi.Input<pulumi.Input<string>[]>;
    publicSubnets?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Region of the AWS node group
     */
    region?: pulumi.Input<string>;
    /**
     * Volume IOPS of the AWS node group
     */
    volumeIops?: pulumi.Input<number>;
    /**
     * Volume size of the AWS node group
     */
    volumeSize?: pulumi.Input<number>;
    /**
     * Volume type of the AWS node group
     */
    volumeType?: pulumi.Input<string>;
}

export interface ClusterNodeGroupsAwNode {
    /**
     * Display name of the node
     */
    displayName?: pulumi.Input<string>;
    /**
     * IP address of the node
     */
    ipAddress?: pulumi.Input<string>;
    /**
     * Is the node active
     */
    isActive?: pulumi.Input<boolean>;
}

export interface ClusterNodeGroupsAzure {
    /**
     * Availability zones of the AWS node group
     */
    availabilityZones?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * CIDR of the AWS node group
     */
    cidr?: pulumi.Input<string>;
    /**
     * Instance type of the AWS node group
     */
    instanceType?: pulumi.Input<string>;
    /**
     * Node location of the AWS node group
     */
    nodeLocation?: pulumi.Input<string>;
    nodes?: pulumi.Input<pulumi.Input<inputs.ClusterNodeGroupsAzureNode>[]>;
    privateSubnets?: pulumi.Input<pulumi.Input<string>[]>;
    publicSubnets?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Region of the AWS node group
     */
    region?: pulumi.Input<string>;
    /**
     * Volume IOPS of the AWS node group
     */
    volumeIops?: pulumi.Input<number>;
    /**
     * Volume size of the AWS node group
     */
    volumeSize?: pulumi.Input<number>;
    /**
     * Volume type of the AWS node group
     */
    volumeType?: pulumi.Input<string>;
}

export interface ClusterNodeGroupsAzureNode {
    /**
     * Display name of the node
     */
    displayName?: pulumi.Input<string>;
    /**
     * IP address of the node
     */
    ipAddress?: pulumi.Input<string>;
    /**
     * Is the node active
     */
    isActive?: pulumi.Input<boolean>;
}

export interface ClusterNodeGroupsGoogle {
    /**
     * Availability zones of the AWS node group
     */
    availabilityZones?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * CIDR of the AWS node group
     */
    cidr?: pulumi.Input<string>;
    /**
     * Instance type of the AWS node group
     */
    instanceType?: pulumi.Input<string>;
    /**
     * Node location of the AWS node group
     */
    nodeLocation?: pulumi.Input<string>;
    nodes?: pulumi.Input<pulumi.Input<inputs.ClusterNodeGroupsGoogleNode>[]>;
    privateSubnets?: pulumi.Input<pulumi.Input<string>[]>;
    publicSubnets?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Region of the AWS node group
     */
    region?: pulumi.Input<string>;
    /**
     * Volume IOPS of the AWS node group
     */
    volumeIops?: pulumi.Input<number>;
    /**
     * Volume size of the AWS node group
     */
    volumeSize?: pulumi.Input<number>;
    /**
     * Volume type of the AWS node group
     */
    volumeType?: pulumi.Input<string>;
}

export interface ClusterNodeGroupsGoogleNode {
    /**
     * Display name of the node
     */
    displayName?: pulumi.Input<string>;
    /**
     * IP address of the node
     */
    ipAddress?: pulumi.Input<string>;
    /**
     * Is the node active
     */
    isActive?: pulumi.Input<boolean>;
}

export interface DatabaseNode {
    connection?: pulumi.Input<inputs.DatabaseNodeConnection>;
    location?: pulumi.Input<inputs.DatabaseNodeLocation>;
    /**
     * Name of the node
     */
    name?: pulumi.Input<string>;
}

export interface DatabaseNodeConnection {
    /**
     * Database of the node
     */
    database?: pulumi.Input<string>;
    /**
     * Host of the node
     */
    host?: pulumi.Input<string>;
    /**
     * Password of the node
     */
    password?: pulumi.Input<string>;
    /**
     * Port of the node
     */
    port?: pulumi.Input<number>;
    /**
     * Username of the node
     */
    username?: pulumi.Input<string>;
}

export interface DatabaseNodeLocation {
    /**
     * Code of the location
     */
    code?: pulumi.Input<string>;
    /**
     * Country of the location
     */
    country?: pulumi.Input<string>;
    /**
     * Latitude of the location
     */
    latitude?: pulumi.Input<number>;
    /**
     * Longitude of the location
     */
    longitude?: pulumi.Input<number>;
    /**
     * Name of the location
     */
    name?: pulumi.Input<string>;
    /**
     * Region of the location
     */
    region?: pulumi.Input<string>;
}

