// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Inputs
{

    public sealed class ClusterNodeGroupsGoogleArgs : global::Pulumi.ResourceArgs
    {
        [Input("availabilityZones")]
        private InputList<string>? _availabilityZones;

        /// <summary>
        /// Availability zones of the AWS node group
        /// </summary>
        public InputList<string> AvailabilityZones
        {
            get => _availabilityZones ?? (_availabilityZones = new InputList<string>());
            set => _availabilityZones = value;
        }

        /// <summary>
        /// CIDR of the AWS node group
        /// </summary>
        [Input("cidr")]
        public Input<string>? Cidr { get; set; }

        /// <summary>
        /// Instance type of the AWS node group
        /// </summary>
        [Input("instanceType")]
        public Input<string>? InstanceType { get; set; }

        /// <summary>
        /// Node location of the AWS node group
        /// </summary>
        [Input("nodeLocation")]
        public Input<string>? NodeLocation { get; set; }

        [Input("nodes")]
        private InputList<Inputs.ClusterNodeGroupsGoogleNodeArgs>? _nodes;
        public InputList<Inputs.ClusterNodeGroupsGoogleNodeArgs> Nodes
        {
            get => _nodes ?? (_nodes = new InputList<Inputs.ClusterNodeGroupsGoogleNodeArgs>());
            set => _nodes = value;
        }

        [Input("privateSubnets")]
        private InputList<string>? _privateSubnets;
        public InputList<string> PrivateSubnets
        {
            get => _privateSubnets ?? (_privateSubnets = new InputList<string>());
            set => _privateSubnets = value;
        }

        [Input("publicSubnets")]
        private InputList<string>? _publicSubnets;
        public InputList<string> PublicSubnets
        {
            get => _publicSubnets ?? (_publicSubnets = new InputList<string>());
            set => _publicSubnets = value;
        }

        /// <summary>
        /// Region of the AWS node group
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        /// <summary>
        /// Volume IOPS of the AWS node group
        /// </summary>
        [Input("volumeIops")]
        public Input<int>? VolumeIops { get; set; }

        /// <summary>
        /// Volume size of the AWS node group
        /// </summary>
        [Input("volumeSize")]
        public Input<int>? VolumeSize { get; set; }

        /// <summary>
        /// Volume type of the AWS node group
        /// </summary>
        [Input("volumeType")]
        public Input<string>? VolumeType { get; set; }

        public ClusterNodeGroupsGoogleArgs()
        {
        }
        public static new ClusterNodeGroupsGoogleArgs Empty => new ClusterNodeGroupsGoogleArgs();
    }
}
