// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Inputs
{

    public sealed class ClusterNodeGroupsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("aws")]
        private InputList<Inputs.ClusterNodeGroupsAwGetArgs>? _aws;
        public InputList<Inputs.ClusterNodeGroupsAwGetArgs> Aws
        {
            get => _aws ?? (_aws = new InputList<Inputs.ClusterNodeGroupsAwGetArgs>());
            set => _aws = value;
        }

        [Input("azures")]
        private InputList<Inputs.ClusterNodeGroupsAzureGetArgs>? _azures;
        public InputList<Inputs.ClusterNodeGroupsAzureGetArgs> Azures
        {
            get => _azures ?? (_azures = new InputList<Inputs.ClusterNodeGroupsAzureGetArgs>());
            set => _azures = value;
        }

        [Input("googles")]
        private InputList<Inputs.ClusterNodeGroupsGoogleGetArgs>? _googles;
        public InputList<Inputs.ClusterNodeGroupsGoogleGetArgs> Googles
        {
            get => _googles ?? (_googles = new InputList<Inputs.ClusterNodeGroupsGoogleGetArgs>());
            set => _googles = value;
        }

        public ClusterNodeGroupsGetArgs()
        {
        }
        public static new ClusterNodeGroupsGetArgs Empty => new ClusterNodeGroupsGetArgs();
    }
}
