// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Inputs
{

    public sealed class ClusterFirewallGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Port for the firewall rule
        /// </summary>
        [Input("port")]
        public Input<int>? Port { get; set; }

        [Input("sources")]
        private InputList<string>? _sources;

        /// <summary>
        /// Sources for the firewall rule
        /// </summary>
        public InputList<string> Sources
        {
            get => _sources ?? (_sources = new InputList<string>());
            set => _sources = value;
        }

        /// <summary>
        /// Type of the firewall rule
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public ClusterFirewallGetArgs()
        {
        }
        public static new ClusterFirewallGetArgs Empty => new ClusterFirewallGetArgs();
    }
}
