// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Inputs
{

    public sealed class ClusterNodeGroupsGoogleNodeArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Display name of the node
        /// </summary>
        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        /// <summary>
        /// IP address of the node
        /// </summary>
        [Input("ipAddress")]
        public Input<string>? IpAddress { get; set; }

        /// <summary>
        /// Is the node active
        /// </summary>
        [Input("isActive")]
        public Input<bool>? IsActive { get; set; }

        public ClusterNodeGroupsGoogleNodeArgs()
        {
        }
        public static new ClusterNodeGroupsGoogleNodeArgs Empty => new ClusterNodeGroupsGoogleNodeArgs();
    }
}
