// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Inputs
{

    public sealed class ClusterNetworkGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// CIDR range for the network
        /// </summary>
        [Input("cidr", required: true)]
        public Input<string> Cidr { get; set; } = null!;

        [Input("publicSubnets", required: true)]
        private InputList<string>? _publicSubnets;
        public InputList<string> PublicSubnets
        {
            get => _publicSubnets ?? (_publicSubnets = new InputList<string>());
            set => _publicSubnets = value;
        }

        /// <summary>
        /// Region of the network
        /// </summary>
        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        public ClusterNetworkGetArgs()
        {
        }
        public static new ClusterNetworkGetArgs Empty => new ClusterNetworkGetArgs();
    }
}
