// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Inputs
{

    public sealed class DatabaseNodesGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("connection")]
        public Input<Inputs.DatabaseNodesConnectionGetArgs>? Connection { get; set; }

        [Input("extensions")]
        public Input<Inputs.DatabaseNodesExtensionsGetArgs>? Extensions { get; set; }

        [Input("location")]
        public Input<Inputs.DatabaseNodesLocationGetArgs>? Location { get; set; }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("region")]
        public Input<Inputs.DatabaseNodesRegionGetArgs>? Region { get; set; }

        public DatabaseNodesGetArgs()
        {
        }
        public static new DatabaseNodesGetArgs Empty => new DatabaseNodesGetArgs();
    }
}
