// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Inputs
{

    public sealed class DatabaseNodeLocationArgs : global::Pulumi.ResourceArgs
    {
        [Input("city")]
        public Input<string>? City { get; set; }

        [Input("code")]
        public Input<string>? Code { get; set; }

        [Input("country")]
        public Input<string>? Country { get; set; }

        [Input("latitude")]
        public Input<double>? Latitude { get; set; }

        [Input("longitude")]
        public Input<double>? Longitude { get; set; }

        [Input("metroCode")]
        public Input<string>? MetroCode { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("postalCode")]
        public Input<string>? PostalCode { get; set; }

        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("regionCode")]
        public Input<string>? RegionCode { get; set; }

        [Input("timezone")]
        public Input<string>? Timezone { get; set; }

        public DatabaseNodeLocationArgs()
        {
        }
        public static new DatabaseNodeLocationArgs Empty => new DatabaseNodeLocationArgs();
    }
}
