// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Inputs
{

    public sealed class DatabaseNodesConnectionArgs : global::Pulumi.ResourceArgs
    {
        [Input("database")]
        public Input<string>? Database { get; set; }

        [Input("externalIpAddress")]
        public Input<string>? ExternalIpAddress { get; set; }

        [Input("host")]
        public Input<string>? Host { get; set; }

        [Input("internalHost")]
        public Input<string>? InternalHost { get; set; }

        [Input("internalIpAddress")]
        public Input<string>? InternalIpAddress { get; set; }

        [Input("password")]
        public Input<string>? Password { get; set; }

        [Input("port")]
        public Input<int>? Port { get; set; }

        [Input("username")]
        public Input<string>? Username { get; set; }

        public DatabaseNodesConnectionArgs()
        {
        }
        public static new DatabaseNodesConnectionArgs Empty => new DatabaseNodesConnectionArgs();
    }
}
