// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Inputs
{

    public sealed class DatabaseNodesConnectionGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("database")]
        public Input<string>? Database { get; set; }

        [Input("externalIpAddress")]
        public Input<string>? ExternalIpAddress { get; set; }

        [Input("host")]
        public Input<string>? Host { get; set; }

        [Input("internalHost")]
        public Input<string>? InternalHost { get; set; }

        [Input("internalIpAddress")]
        public Input<string>? InternalIpAddress { get; set; }

        [Input("password")]
        private Input<string>? _password;
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("port")]
        public Input<int>? Port { get; set; }

        [Input("username")]
        public Input<string>? Username { get; set; }

        public DatabaseNodesConnectionGetArgs()
        {
        }
        public static new DatabaseNodesConnectionGetArgs Empty => new DatabaseNodesConnectionGetArgs();
    }
}
