// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pgedge.Pgedge.Inputs
{

    public sealed class DatabaseNodesExtensionsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("errors")]
        private InputMap<string>? _errors;
        public InputMap<string> Errors
        {
            get => _errors ?? (_errors = new InputMap<string>());
            set => _errors = value;
        }

        [Input("installeds")]
        private InputList<string>? _installeds;
        public InputList<string> Installeds
        {
            get => _installeds ?? (_installeds = new InputList<string>());
            set => _installeds = value;
        }

        public DatabaseNodesExtensionsGetArgs()
        {
        }
        public static new DatabaseNodesExtensionsGetArgs Empty => new DatabaseNodesExtensionsGetArgs();
    }
}
