// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getBackupStores(opts?: pulumi.InvokeOptions): Promise<GetBackupStoresResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("pgedge:index/getBackupStores:getBackupStores", {
    }, opts);
}

/**
 * A collection of values returned by getBackupStores.
 */
export interface GetBackupStoresResult {
    readonly backupStores: outputs.GetBackupStoresBackupStore[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
export function getBackupStoresOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetBackupStoresResult> {
    return pulumi.output(getBackupStores(opts))
}
