// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Data source for pgEdge cloud accounts.
 */
export function getCloudAccounts(opts?: pulumi.InvokeOptions): Promise<GetCloudAccountsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("pgedge:index/getCloudAccounts:getCloudAccounts", {
    }, opts);
}

/**
 * A collection of values returned by getCloudAccounts.
 */
export interface GetCloudAccountsResult {
    readonly cloudAccounts: outputs.GetCloudAccountsCloudAccount[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
/**
 * Data source for pgEdge cloud accounts.
 */
export function getCloudAccountsOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetCloudAccountsResult> {
    return pulumi.output(getCloudAccounts(opts))
}
